blank_issues_enabled: true
contact_links:
  - name: Support on Microsoft Teams
    url: https://teams.microsoft.com/l/team/19%3a6upqAkbIoz2YZVfl85j58g0WrINu4R5sq0-Q6OaaWS01%40thread.tacv2/conversations?groupId=f46d31a2-d725-4570-93de-1a96373dcd4b&tenantId=935c6c4c-135c-4711-b2ee-8c362d3ee102
    about: Get support, ask and answer questions in the dedicated team
  - name: General feedback
    url: https://forms.office.com/r/2sx7Vv6Xnh
    about: Submit general feedback via the online form here
